language: smalltalk
sudo: false

os:
  - osx
  - linux

smalltalk:
  - Pharo-7.0
  - Pharo64-7.0
  - Pharo-8.0
  - Pharo64-8.0

matrix:
  fast_finish: true
  allow_failures:
    - smalltalk: Pharo-8.0
